### ISSUE TITLE
Replace plugins using Curl commands with Requester usage

### ISSUE THREAD

**Issue by flabbergastedbd** [owtf/reboot#10]
I think it is better to use the requester module instead of curl and obviously for this the requester module has to be improvised.

**Comment by DePierre** [comment]
@tunnelshade Are you talking about the plugins running curl commands like OWASP-CM008? Or is it broader than that?

In a more general way, I think we should avoid as much as possible writing bash code within python.

**Comment by flabbergastedbd** [comment]
Plugins first, we use lot of curl commands, where as we should be doing it with our requester module

**Comment by DePierre** [comment]
I agree on that yes.

**Comment by viyatb** [comment]
This issue was moved to owtf/owtf#909
