### ISSUE TITLE
Headless Browser in requester

### ISSUE THREAD

**Issue by flabbergastedbd** [owtf/reboot#11]
We have a simple requester as of now which is good for sending HTTP requests. It will be great to also have a headless browser factory inside the requester. The typical flow when requested for an authenticated browser instance
- The "Requester" module checks if there is any login parameters provided (i.e creds or script or whatever)
- Create a browser instance and do the necessary login stuff
- Handle the browser to whosoever asked for it
- When called to close the browser, do a clean logout and kill the browser instance.

The only small problem here is that the plugin using the browser instance should be careful of not logging out. To avoid this we can actually wrap certain methods of PhantomJS browser. What do you guys think?

**Comment by viyatb** [comment]
This issue was moved to owtf/owtf#910
