### ISSUE TITLE
Reboot Procedure

### ISSUE THREAD

**Issue by DePierre** [owtf/reboot#12]
Since the discussion about the reboot project is starting, we should agree on the procedure to follow from the issue page, to the code, stopping by the documentation.

I would like to propose the following:
1. Start the **discussion on GitHub Issue webapge** (like we are currently doing)
2. Once the discussion becomes mature (e.g. a precise idea) we **label it as 'Wiki'**
3. A 'Wiki' issue is then **reported to the Wiki page**
4. The **revision is done in the issue** labelled as 'Wiki'
5. Once the revision is done, we **label the issue as 'Code'**
6. A 'Code' issue is then **reported to the code base**

**Comment by flabbergastedbd** [comment]
Seems fine to me
