### ISSUE TITLE
Roadmap for the distributed architecture implementation

### ISSUE THREAD

**Issue by viyatb** [owtf/reboot#16]
This can be good place to discuss/debate the new distributed architecture and its following components:
- Core architecture (master, manager, slave)
- The intercomponent messaging framework - eg. RPC, JSON-RPC, etc
- Internal analytics/monitoring/profiling (new feature)
- Datastore

This could the starting point for the first draft. @marioskourtesis?

**Comment by DePierre** [comment]
@delta24 well I think that such discussion is in fact taking place all over the GitHub issue webpage. In fact, each bullet point of your comment should be a standalone issue

**Comment by viyatb** [comment]
I wanted this in one place so that @marioskourtesis can start fast from here in his core implementation + proposal instead of searching in multiple issues.

**Comment by DePierre** [comment]
@delta24 I think going through the list of open issues should be easy for @marioskourtesis to pick ideas.

What we could do with **this** issue to for @marioskourtesis to write here his plan or table of contents for instance. Should we rename the issue?

**Comment by viyatb** [comment]
Yes, I had exactly that in mind. :)

**Comment by viyatb** [comment]
This issue was moved to owtf/owtf#914
