### ISSUE TITLE
Redesign the web interface

### ISSUE THREAD

**Issue by viyatb** [owtf/reboot#18]
This is just the placeholder issue for web interface redesign.

Reduce clicks and have a more natural flow  ⇒ This refers to the fact that the current interface is not user-friendly, and can be modified to increase productivity while reducing redundancies and improving consistency.
- The main OWTF report uses elements known as `accordions` to represent findings of the plugins. The accordion element is not scalable: it is not a user-friendly technique to represent hundreds of rows of plugins.
- The goal here is to come up with an interface that is user-friendly, scalable, and maintainable.
  - CSS standards: Currently OWTF uses a heavy-CSS framework, Twitter Bootstrap to render elements. Twitter Bootstrap includes many unnecessary elements and is so heavy-handed, so prescriptive, that it is actually a nuisance to modify. It’s easier to use the defaults.
  - Also write everything in SASS (Syntactically Awesome Stylesheets), reducing redundancy and development time.and increasing consistency. SASS is very easy to write and is a more maintainable alternative.
  - Use compass (SASS -> CSS compiler) to compile everything (concatenate) the stylesheets and minify them whenever regenerating.

**Comment by DePierre** [comment]
I agree that the current interface isn't the most user-friendly of all.

Though I believe that we should start drawing the interface on paper (or gimp, paint, ascii-art whatever) and then ask someone with good skills in webui-friendliness.

For instance, OK accordions are bad but what else could we use? I have personally no idea :8ball:

**Comment by viyatb** [comment]
I have some, I'll upload some of them soon :)

**Comment by DePierre** [comment]
@delta24 Glad to hear that :)

**Comment by flabbergastedbd** [comment]
+1 on using a light weight alternative to Bootstrap. I played with [purecss.io](http://purecss.io) a bit and that is really lightweight. I am ready to think of alternatives.
- My problem is with `compass` and `sass`. Both need ruby gems as a developer dependency. For every CSS change we have to recompile them. Isn't this too much for a [single custom css file](https://github.com/owtf/owtf/blob/develop/includes/css/stylesheet.css)?

Please suggest any other CSS frameworks, that you have in mind. Lets not go for SASS and compass

**Comment by viyatb** [comment]
Python bindings for `libsass` (C/C++ implementation of SaSS reference - originally implemented in Ruby) are available. See https://github.com/dahlia/libsass-python. 
I'll post a few other CSS frameworks soon.

**Comment by viyatb** [comment]
Already in progress.
