### ISSUE TITLE
New installation method

### ISSUE THREAD

**Issue by viyatb** [owtf/reboot#19]
The current method assumes that you are installing on a clean Kali VM. But in the recent version of Kali ie. 2.0, they have `chown` the `dist-packages` directory so that other installed tools do not break.
One such issue: https://github.com/owtf/owtf/issues/509
IMHO this is a good time to come up with the new installation plan using `virtualenv`.

**Comment by DePierre** [comment]
It would be interesting to look a little bit more into virtualenv indeed.

With @alexandrasandulescu's work, we are step by step getting rid of this distro-dependent stuff so would be nice to keep it that way. I would like to see a Kali-independent installation process, and then we would have a secondary script/process to install what's needed on Kali.

What do you think?

**Comment by alexandrasandulescu** [comment]
I thought about this and yeah, the distribution package manager and pip install do not work well when both are used. We can try to isolate owtf from the package manager. virtualenv is a good idea because we cannot control the packages already installed on user's system ( the docker is a way of doing this, but not everyone is familiar with it)

**Comment by viyatb** [comment]
Great suggestions! @DePierre @alexandrasandulescu : I think I can help out a bit after 27th Aug - when my university exams end :)

**Comment by DePierre** [comment]
Personally I don't feel up for such task. We have a lot going on with the reboot project and I would prefer working on other aspects, such as the plugin system for instance.

**Comment by flabbergastedbd** [comment]
We will switch to using virtualenv. Other than that other changes are required?

**Comment by viyatb** [comment]
A logical code structure so that packaging for different systems ie. Fedora-based, Debian-based, Archlinux,  etc is easier.
One of them is in progress, Archlinux **AUR** package by @alexandrasandulescu.

**Comment by viyatb** [comment]
Similar issue https://github.com/owtf/owtf/issues/516.
Can anyone try the current setup in a fresh Kali 2.0 VM ?

**Comment by viyatb** [comment]
This has already been done in the latest master.
