### ISSUE TITLE
OWTF entry points in /bin directory

### ISSUE THREAD

**Issue by DePierre** [owtf/reboot#20]
The current OWTF project has a framework where all the code base is written and an `owtf.py` python file at the top to deal with it. The framework exposes the API for OWTF and `owtf.py` solely exposes the CLI options.

While this is what we should do for the reboot project as well, I think we should move `owtf.py` under a directory named `/bin` and split `owtf.py` into two scripts:
- One exposing the WebUI only
- One exposing the CLI only

While both scripts will consist of the same things (i.e. doing the same actions), it would make the parsing of the options easier, and reduce the maintenance cost if they were split IMO.

So we would have something like:

``` bash
.
├── bin
│   ├── owtfcli.py
│   └── owtfwebui.py
└── framework
```

(Maybe I am overthinking that and we could keep the current organisation)

**Comment by flabbergastedbd** [comment]
I like the splitting into two files. Let us keep those two files in the root directory itself?

**Comment by DePierre** [comment]
I thought about saving them in './bin' to make it easier to crawl the project directory. Also, it would make sense if when then aim to place these scripts to '/bin/', using pip's bin feature.

**Comment by flabbergastedbd** [comment]
Btw you are forgetting the scripts for starting "grunts" :P

**Comment by viyatb** [comment]
Already done in the main repo.
