### ISSUE TITLE
MiTM Proxy

### ISSUE THREAD

**Issue by marioskourtesis** [owtf/reboot#22]
Hello Team,

Do we have any project plan about the new MiTM proxy?
We can not use the same proxy when we are gonna have distributed nodes.

Kind Regards

**Comment by flabbergastedbd** [comment]
Already done @marioskourtesis https://github.com/owtf/reboot/wiki/Proxy-Architecture

**Comment by marioskourtesis** [comment]
Thank you Bd!
It would be cool If Grunts update their cache for other Grunts every now
and then.
This draft for me is enough to move on with the proposal atm.

Kind Regards
Marios

**Comment by DePierre** [comment]
I thought that the point of having a Hero -> Grunt -> Peon architecture was to build each component to be independent on their respective level. Why would we have one Grunt update its cache for other Grunts?

Maybe I misunderstood you @marioskourtesis. Could you be more specific?
