### ISSUE TITLE
Workers/Slaves Naming

### ISSUE THREAD

**Issue by flabbergastedbd** [owtf/reboot#5]
As of now all the information related to a worker is in memory. Since we are planning for a distributed version, @DePierre has a way of exchanging information between **slave** and master node.

I also want us to pick the names carefully. i.e A single slave node can have multiple plugin processes running. So is the name **slave** intuitive? I have one scheme in idea which has **Oracle Node** is the main node and then we can have **Manager Nodes** (the present slave ones) and each manager will have "Worker Processes" under it. Not a great scheme but something that can be brainstormed upon

**Comment by DePierre** [comment]
I wish to use Warcraft 3 unit names for the hierarchy mostly for fun. One possibility could be:
- Peon for the lowest element in the chain, i.e. the worker process
- Grunt for the element just above, i.e. worker manager
- Hero for the highest element, i.e. Master

**Comment by viyatb** [comment]
IMHO, it would easy to remember something based on army ranks :P,  
- Private - worker process
- Colonel - worker manager
- <s>General</s> Commander - master node

**Comment by flabbergastedbd** [comment]
Is "General" not too general? :P

**Comment by DePierre** [comment]
Let's keep the army out of the project.

**Comment by viyatb** [comment]
This issue was moved to owtf/owtf#906
