### ISSUE TITLE
Usage of Bower

### ISSUE THREAD

**Issue by flabbergastedbd** [owtf/reboot#6]
I want to suggest usage of bower to manage our third party UI dependencies (Like JS MVC framework, CSS framework, Jquery, icons etc..) for the following reason
- [Bower](http://bower.io) will keep track of the version that we are using which will allow us to upgrade using single command. This will only be a developer dependency and not a OWTF dependency

I will die to have a python alternative to bower for this kind of handling. Please suggest!

**Comment by DePierre** [comment]
Isn't this way too much for us? What are our web dependencies for the UI? How many? 3? 5?
IMHO with so few we don't need to use a bulldozer to manage them. We should try to KISS.

**Comment by flabbergastedbd** [comment]
@DePierre We have 10+ such JS+CSS dependencies. From the last experience with these I remember the pain to update those. Now the list that I can recall directly
- Bootstrap or Any other CSS framework
- Jquery
- MVC JS Framework
- Font Awesome
- DataTables
- Few jquery third party plugins like (highlighter etc..)
- Ckeditor
- Spinner
- Font Awesome Icons
- FileSaver

The difficult part is not using them first time but updating them every other time

**Comment by viyatb** [comment]
+1

**Comment by DePierre** [comment]
@tunnelshade meh, not sure that it is still needed. Libs like font awesome and font awesome icons (they are different?) dont need to be updated often. Same with bootstrap (if we keep it), same as most of ones listed in your comment.

IMO it's not really needed. Let's be honest here, how many commits in the OWTF branches correspond to update of UI dependencies? Too few to make Bower useful.

**Comment by flabbergastedbd** [comment]
@DePierre Font Awesome Icons and Font Awesome seperately, it was a mistake. There are no commits for updating libraries because we never wanted to go through the pain of downloading the new version and replacing the old one. You can see that our media dependencies are very outdated.

What bower brings to the table is one command update and ability to rollback without all the hassle.

Maybe I didn't stress it enough. It is a developer dependency. If you don't like using it then you can just avoid installing it. No problem with working or development of OWTF. All we have is one extra file called `.bowerrc`

**Comment by DePierre** [comment]
@tunnelshade You stressed that it's a developper dependency enough, I got it ;)
There are some commits for dependency. I remember one during GSoC last summer about Font Awesome.

I am not saying that we shouldn't use bower, I simply wanted to ask insightful questions about whether it is really needed or not. Is it a problem that our WebUI dependencies are outdated? When we installed them, they fitted their jobs and still do now.

**Comment by flabbergastedbd** [comment]
Yes, outdated things are problem like in case of CKEditor which brings in some new functionality or Font Awesome which brings some new fonts or new Bootstrap which brought some layout changes. We miss out on all these because the work to update these is huge

**Comment by DePierre** [comment]
@tunnelshade How huge is this? Font Awsome is simply changing a file to another and for what? One icon.
Bootstrap adding a new layout? Might be interesting to look into it but still, if they didn't bump their major version number, changing the file should be enough if you really want to update it.
I don't know about CKEditor.

**Comment by 7a** [comment]
Each library may require us to update many files, this takes time so we
never did it. Security vulnerabilities are another cause of concern here.
With this in mind, +1 for bower from me :)

**Comment by viyatb** [comment]
Bower is deprecated now, and we already use webpack in the develop branch.
