### ISSUE TITLE
Putting /doc in the main repo

### ISSUE THREAD

**Issue by flabbergastedbd** [owtf/reboot#7]
Though I wrote the complete user docs initially, it is difficult for most of the people to add changes to documentation in a different repo. So I think it is a better idea to put the user docs in the main repo where  we can side by side update the docs when a relavent change is made.

**Comment by viyatb** [comment]
I think the user docs will go to the Github `wiki`, but the API and other internals documentation (generated from **Sphinx**) will go to `/docs` in the repo.

**Comment by flabbergastedbd** [comment]
User docs are the ones I am talking about in `doc`. The sphinx generated developer docs need not be stored on the repo, they will be generated and pushed to something like readthedocs.org

**Comment by viyatb** [comment]
Done.
