### ISSUE TITLE
Slave authentication

### ISSUE THREAD

**Issue by flabbergastedbd** [owtf/reboot#8]
Planning on using client certificates to authenticate the slaves. It will be easier to generate certs for each slave and moreover tornado has inbuilt facility to specify client certs in http requests. Check [this](http://tornado.readthedocs.org/en/latest/httpclient.html#tornado.httpclient.HTTPRequest) on providing client key and cert in tornado

**Comment by viyatb** [comment]
+1 must have. 
Or we can have an `agent` service that authenticates each slave to the master.

**Comment by DePierre** [comment]
We definitely need the advice of some crypto experts on this matter. It's way out of my league tbh and I don't want to blindly trust some student on that matter and see our architecture being insecure on our first release.

**Comment by viyatb** [comment]
This issue was moved to owtf/owtf#907
